FROM node:22-alpine AS base
RUN corepack enable
WORKDIR /workspace

FROM base AS dependencies
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile=false

FROM dependencies AS build
COPY . .
RUN pnpm nx build api

FROM node:22-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app
RUN addgroup --system tarweej && adduser --system --ingroup tarweej tarweej
COPY --from=build /workspace/dist/apps/api ./
COPY --from=dependencies /workspace/node_modules ./node_modules
USER tarweej
EXPOSE 3000
CMD ["node", "main.js"]
